### PR TITLE
Add Default value for features

### LINKED ISSUE #21: Feature request: Default value when tracking
For some things I track, I want to have multiple options, but there's in one which I almost always use. It would be nice if I could configure it to use that value by default when I click the little plus next to it - that way I have the conveniences of pure time-tracking with the option to select another value by editing or when using the track all button.

### PR DESCRIPTION
**Pull request by xerus2000**
Not yet working, very WIP

Fixes #21

### CODE REVIEW

**Comment by SamAmco** [comment]
So as I understand it the best way to go about this would be to get rid of the "Date and Time Only" feature type all together and just add the option of a default value to the continuous feature type. That way you can always go back and edit the values as needed and it will not ask you for a value as default. This should solve issue #20 also.

Some extra considerations here:

- [ ]  We need to make sure the user understands what behaviour to expect with any given configuration and that they aren't confused the first time they use the app. Clearly state that they won't be asked for a value if they set a default.

- [ ]  What is the behaviour of the quick track function if there are default valued features in the track group. I would assume that it would present you with an input box but the input box would already be filled with the default value.

- [ ]  We need to make sure we account well for migrating existing databases. We don't want to break peoples graphs, track groups, etc..

**Comment by Xerus2000** [comment]
Sounds great :) I also thought about removing date&time tracking entirely, but I thought it may make sense to keep it in the front-end for better UX but unify it in the backend.

**Comment by SamAmco** [comment]
I think it's probably simplest to have only continuous and discrete feature types and an optional default value. There's actually no reason multiple choice can't have this also so it can be a generalized concept. I would add an extra section to the add feature fragment that allows you to specify a default and explains clearly what this will do.

**Comment by Xerus2000** [comment]
yep, then we agree here, I'll see when I get to it ^^

**Pull request closed without merging**
