### PR TITLE
Add app widgets

### LINKED ISSUE #4: Feature request: Widgets
Hi @SamAmco, thanks a lot for the app! Always wished for something like this.
One feature I'd be happy to have:

Android widgets for the various tracks. So a user – for example for numerical input – only has to tab the correct widget and it counts. Would simplify the process and encourage tracking.

### PR DESCRIPTION
**Pull request by pizzapim**
I'm implementing functionality first and after that I can look at the design.

Functionality to cover still:

- [x] Spinner in configure activity to select what to track
- [ ] Don't open the main app when opening the track dialog from the widget
- [x] Disable widgets when a feature is deleted
- [x] Adopt the feature card layout for the widgets
- [x] Indicate when widget is disabled in layout
- [x] Full widget button

Fixes #4

### CODE REVIEW

**Comment by pizzapim** [comment]
@SamAmco 
I'm a little stuck right now. I have a spinner in the configure activity to select what to track, but it won't show any values in de UI. I reused most of the code from elsewhere in the app so I'm not sure what's going wrong. Do you think you could take a look? The values are added in widgets/TrackWidgetConfigure.kt in the onCreateView method.

**Comment by SamAmco** [comment]
Ah well done for getting this far. I will try and take a look tomorrow, hopefully I can unblock you.

**Comment by SamAmco** [comment]
Ok so I managed to hack it and get it roughly working. What I think is happening is that when you call:

        `binding = TrackWidgetConfigureBinding.inflate(layoutInflater)`

Inflate is calling onCreateView and therefore binding is not yet actually set in onCreateView. I managed to get your code working by cutting and pasting everything from the body of onCreateView  into onCreate just below the above line (obviously without the return null part).

**Comment by pizzapim** [comment]
@SamAmco 
Thanks for the help! The problem was that I created two layouts, and was using the one without the binding.

**Comment by SamAmco** [comment]
Glad you figured it out

**Comment by pizzapim** [comment]
@SamAmco 
I think the PR is ready for a review. It has grown to a lot of LOC :) I have added some comments here and there, but please ask if something is not clear. I found that app widgets are very different from normal Android activities so it's very different from the rest of the app. Also I'm still a noob so I probably made some architectural mistakes too :)

One thing I could not fix is that the input dialog from the widget opens the main app activity. Ideally this opens a one shot dialog. I tried every option but alas.

**Comment by SamAmco** [comment]
Hey sorry I totally missed your last comment there somehow. I will try to take a look at this soon. Thanks.

**Comment by SamAmco** [comment]
Hey so I had a look over your changes and it's looking pretty good so far. The code looks pretty good to me at a glance although I must admit I've never made an app widget before so I should probably do some reading up and just check there's nothing missing/incorrect. I do have a few issues/comments though:

- [ ] Can you please put the license doc at the top of each new file. You can find an example in most other files in the project. (You can set up Android Studio to automatically add this to every file for you)
- [ ] There isn't generally enough space to see the full feature name on the widget so perhaps the default size should be bigger? 
- [ ] I think we should move the plus button to the bottom right of the widget because even when you expand a widget with a long name the name text tends to overlap with the button graphic (this shouldn't ever happen)
- [ ] Can we add a little colour to the widget? maybe just use one of the apps primary colours for the background rim or something? 
- [ ] The plus button is small. I think it would feel more consistent if it was the same size as shown on the cards in the app.
- [ ] The create widget activity looks a bit wrong atm, you have a lot of blank space on that screen and the size of the spinner looks a lot larger than other similar spinners in the app. In the interest of consistency I think it would be better to use a dialog here with a title, a spinner, an "add" button in the bottom right and a "cancel" button in the bottom left. Again try to use similar padding and dimensions used in other similar dialogues. 
- [ ] Can we support the Date & Time only tracking behaviour. If you create a Date & Time only feature in the app right now you'll notice the track button is blue and tapping it simply adds a 1 in the history at the current date and time without opening a dialog. Ideally this should behave the same way for a widget, I think it would annoy users otherwise.

On a final note I can't replicate this issue you're having of the main app opening, that never seems to happen on my device. Did you fix this? Did you want me to look into it? If so, can you give me a device spec and maybe a steps to reproduce on this? 

Once again thanks for all your work on this so far. I know the above probably seems like a lot but actually I think the work you have done is looking pretty darn good and very close to something I would want to merge.

**Comment by pizzapim** [comment]
Thanks for the comments. I'll take a look in probably 1-2 weeks as I'm a bit busy lately, but I understand all the points you make. I'm glad it's mostly UI/UX as the actual logic was the real problem :)

On the subject of the main app opening: the steps to reproduce are opening the main app, then pressing your home button to return to the home screen, then clicking the button in the widget which then opens the app. This was on Android 8.1.0 on a Motorola Moto G5.

**Comment by pizzapim** [comment]
@SamAmco 
Been awhile, but I think I got everything taken care of. Please check it out again and comment!

**Comment by SamAmco** [comment]
Thanks Pizzapim, I will take a look soon :)

**Comment by SamAmco** [comment]
Hi @pizzapim I have merged your PR into a branch from which I will make a couple of small updates before merging to master ready for release. Looks like great work! Thank you very much for your contribution.

Just FYI I'm installing the all-contributors bot: https://github.com/all-contributors/all-contributors and I intend to keep a record of contributors on the README page.

**Comment by SamAmco** [comment]
@all-contributors please add @pizzapim for tracking widgets

**Comment by SamAmco** [comment]
@all-contributors please add @jakebolam for infra and code

**Comment by SamAmco** [comment]
@all-contributors please add @pizzapim for infra and code

**Comment by pizzapim** [comment]
Hey @SamAmco ,

Awesome! Looking forward to seeing the update on fdroid :)

**Pull request merged**
