### PR TITLE
Fixed those blocked texts on the about page

### PR DESCRIPTION
**Pull request by yuhuitech**
Dear developer:

Hello! I am the creator of issue #121, and I have fixed those blocked texts on the about page by using a ConstraintLayout to make them more responsive. I would appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!

Here is the screenshot after my changes:

copy

Thanks again! Have a nice day! :)

### CODE REVIEW

**Comment by franklinbill** [comment]
Great! I agree with your fix @yuhuitech 👍👍

**Comment by SamAmco** [comment]
Hi, thanks for pointing out this problem. I have merged my own fix for this into master now so i will reject this PR. I took a look at your solution, and it was better than the original but it did allow for text to overlap in some cases. Thank you anyway.

**Comment by SamAmco** [comment]
@all-contributors please add @yuhuitech for code

**Comment by yuhuitech** [comment]
@SamAmco Thank you so much for adding me as a contributor, but I would like to know in which circumstance those strings on this page will overlap together? Is it because of another screen size or? 
Thanks again!! :)

**Comment by yuhuitech** [comment]
Could you please send me a screenshot of your aforementioned circumstances if it is possible and convenient for you? Thanks! :)

**Comment by SamAmco** [comment]
essentially if i sqeeze the layout really tight then your text views will overlap because they are not constrained to each other but rather constrained to the start and end of parent: 

image

It's a very tricky layout to do well actually and I'm not convinced my solution was perfect, but the text views are constrained so they can't overlap at least.

**Comment by yuhuitech** [comment]
OK, I understand, and thank you again for informing me of this! :)

**Pull request closed without merging**
