### PR TITLE
Fix: Moving average window is one day longer 

### PR DESCRIPTION
**Pull request by hhpmmd**
Fixes issue #70 .

Okay so the fix was very easy (change <= to < ) (line 334).

After finding this fix i got the (unreasonable) urge to add some extra code so that the behavior is unchanged for non-aggregated data (plot-when-tracked). So I came up with an idea to find out whether the input data is aggregated or not, so the function can behave differently for the two cases (agg, non-agg). Long story short: the code i wrote to differentiate the inputs doesn't work (no errors, but crashes the app), so I left it as a comment for future reference (together with some explanations) in case someone wants to implement different behavior for the different cases. What that should be and if its 'good' is a different question.

I think the fix is good and the edge case where the fix would actually impact the plot-when-tracked data is very rare.

Whether the comment should be kept in the code is a different question. Maybe remove the code (since it non-working) and replace it with some pseudo code, or just remove the whole comment. I myself am not sure if i want it there.

### CODE REVIEW

**Comment by hhpmmd** [comment]
**I fixed the bug in the outcommented code.** 

Maybe now it makes sense to keep the comment..

**Comment by SamAmco** [comment]
So with this change Daily moving average + Daily totals = Daily totals .. So you must have a moving average period greater than the totalling period in order for it to mean anything. I suppose this could be considered more correct, I'm not sure how many users depend on the existing behaviour vs how many find it confusing. Also with this change you don't have the option to have totals averaged with their last value where as in the existing code you do. It seems a shame to remove that feature ... /bug? haha

FYI there is a failing unit test after this change.

**Comment by hhpmmd** [comment]
> Daily moving average + Daily totals = Daily totals

I mean yeah, if a three day average takes three days then a one day average takes one day.. I see that the one day average is kind of weird then, maybe it makes sense to make the window for the one-day-average a second longer, so it averages two days when using the aggregation.

**Comment by hhpmmd** [comment]
> Also with this change you don't have the option to have totals averaged with their last value where as in the existing code you do. 

Could you explain this more? I am not sure I understand.

I personally use the plot daily averages with 3day, weekly and monthly averaging windows, and with this new change the 3day window and the weekly window behave as expected.

**Comment by hhpmmd** [comment]
I also agree, that changing existing plots from users by changing the averaging is sub optimal, but so is finding out that the three day average averages 4 days when using plot-daily-totals.

**Comment by hhpmmd** [comment]
Regarding the test: I should have ran the tests myself, mb

There are two (reasonable) ways to fix the testcase:

1. Make the new result the right one
2. Increase the averaging window by a second, which results in the old values.
3. (potentially unreasonable) change the average function to use the `input_is_aggregated_total_data` flag to increase the window by a second, resulting in the old values

I think in a raw mathematical sense (if we don't come up with a different solution here) the first option makes the most sense.

**Comment by SamAmco** [comment]
Yes you make a good point. Let's just fix the test by making the new value the expected value and merge.

**Comment by hhpmmd** [comment]
I updated the test.

**Comment by SamAmco** [comment]
Thank you, merged :) Good work

**Pull request merged**
