### PR TITLE
add: allow to overwrite default values #106

### PR DESCRIPTION
**Pull request by stheid**
implements #106

### CODE REVIEW

**Comment by SamAmco** [comment]
Sorry i replied to your issue before i saw you had already implemented. Looks good (i haven't tested but i assume you have.) The only other thing is whether this can be added to the tracking widget? Do you mind taking a look at this also? If not then i can probably just merge without.

**Comment by stheid** [comment]
I am not sure what you are refering to. But i would do it if you tell me what to do. I am not so much a UI guy, so i am not sure what exactly a widget is in that context :D

Where i implemented it is the trackergroup and than when clicking on the button of the tracker card. And yeah i tested it.

**Comment by SamAmco** [comment]
I will get back to you on #42 soon. I need to think about it a little. 

Your implementation looks correct but tracking widgets are a different thing. You can create a tracking widget on your homescreen that allows you to track without opening the app. The view for this is generated by TrackWidgetProvider and it launches TrackWidgetInputDataPointActivity. I suspect you can not do the same thing here because I think the OS probably consumes the long press event to show the option to move/delete the widget. I'm not sure what is best in this case like I say, maybe it's enough to leave it how it is but I thought I should make you aware of it, perhaps you have a better idea?

**Comment by stheid** [comment]
Ah now i understand the issue. I might have a look in the upcomming week, but i think this can be treated as "another issue", as my implementation does not break that behaviour, just does "not solve it as well" :D

**Comment by SamAmco** [comment]
@allcontributors please add @stheid for code

**Pull request merged**
